### PR TITLE
Android: memory leak issue fixed

### PR DESCRIPTION
**Pull request by ronit-kadwane**
- added `stopPlayback()` method for android.
- use this method to release memory
- the player to avoid a potential memory leak

### CODE REVIEW

**Comment by manse** [comment]
Playback control is controlled by `play: boolean` props, so I don't want to add a method about playback. 
I think the same effect can be obtained by calling `stopPlayback` on switching videos at `loadVideo`.
https://github.com/manse/react-native-brightcove-player/blob/d3a3d3be6b5928b3edf40ae3741342fa38b902af/android/src/main/java/jp/manse/BrightcovePlayerView.java#L307

**Comment by ronit-kadwane** [comment]
@manse Yes, I agreed, We can call `stopPlayback` on switching videos at `loadVideo`. 
but in my opinion, it's not the proper way to handle memory leak. We suppose to expose method for it. so one can handle it according to their cases.

**Comment by jariwalabhavesh** [comment]
@manse : I think instead of adding stopPlayback in loadvideo method. The separate method will be more convenient for library users. Users will free to use where ever they need to stopPlayback.

**Comment by manse** [comment]
OK then, could you please implement stopping playback (with releasing memory) in iOS?
https://github.com/ronit-kadwane/react-native-brightcove-player/commit/d3a3d3be6b5928b3edf40ae3741342fa38b902af#diff-0a799f5d684ca54dc6b30f07ec2a41acR115

**Comment by ronit-kadwane** [comment]
@manse Thanks for agreeing with the thought process.
Let me inform you first `stopPlayback` method is only for Android SDK, it is not for iOS SDK.
So, we don't need to worry about iOS.
I have already tested `stopPlayback` method for both the platform and it is working seamlessly. So you can merge it.
Thank you.

**Comment by ronit-kadwane** [comment]
@manse 
You will be more clear if You read BrightCove player documentation and official example on GitHub.
They are not able to handle the memory leak issue internally on the Android platform that's why 
they have provided `stopPlayback` method just for the Android platform.
For iOS its handle by internal SDK that's why they don't have `stopPlayback` method for iOS.

As far as the plugin method is concerned, I have developed only for Android as it's needed in the Android only. 
Just to look similar I have created a method in iOS as well but it is an empty function as iOS does not have `stopPlayback` method in SDK.

I hope now you would be bit clear.

**Comment by Salar-g** [comment]
Thanks @ronit-kadwane your code saved my project. I believe this pull request should ve been merged

**Comment by ramzus077** [comment]
@ronit-kadwane  I am not understand where to call the function stopPlayback() in my react-native code

**Comment by nicoladj77** [comment]
@ronit-kadwane where should I call stopPlayback? when unmounting?can I simply out it in the componentWillUnmount metgod here?

```
  componentWillUnmount = Platform.select({
    ios: function() {
      NativeModules.BrightcovePlayerManager.dispose(
        ReactNative.findNodeHandle(this)
      );
    },
    android: function() {}
  });
```

**Pull request closed without merging**
